site_name: ITWay
site_description: Projet de fin d'année - ITWay
site_author: Firase JEMAA & Najet BOUKADOUR
repo_url: https://github.com/<ton-utilisateur>/<nom-du-repo>  # Remplace aussi
repo_name: GitHub

theme:
  name: material
  language: fr
  palette:
    - scheme: slate       # Thème sombre
      primary: black       # Couleur principale (sobre)
      accent: lime        # Couleur accent (flashy)
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
    - scheme: default     # Thème clair (optionnel)
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: 🔗
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.keys

nav:
  - Accueil: index.md
  - Phase 1:
    - Présentation: phase1.md
  - Phase 2:
    - Présentation: phase2.md
    - Conception du projet: conception.md
    - Infrastructure: infra.md
    - Prérequis: prerequis.md
    - Routeurs: 
        - Configuration des Routeurs: routeurs.md
        - CORE-RT: core-rt.md
        - DMZ-RT: dmz-rt.md
    - SRV:
        - SRV-PKI: ./srv/pki.md
        - SRV-MAIL: ./srv/mail.md
    - DMZ: 
        - Objectif: ./dmz/dmz.md
        - DMZ-DNS: ./dmz/dns.md
        - DMZ-RPROXY: ./dmz/rproxy.md
        - DMZ-WEB: ./dmz/web.md
        - DMZ-SMTP: ./dmz/smtp.md
  - Phase 3:
    Phase 3: phase3.md

